:set clipboard=unnamedplus,unnamed
:set number
:set relativenumber
:set autoindent
:set tabstop=4
:set shiftwidth=4
:set smarttab
:set softtabstop=4
:set mouse=a
:set encoding=UTF-8
:set incsearch
:set termguicolors
:set scrolloff=20
:set wildignore+=*.pyc,*.o,*.obj,*.svn,*.swp,*.class,*.hg,*.DS_Store,*.min.*,__pycache__,*.git,.venv,.tox,.mypy_cache
